routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\BeasiswaController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\RegisterBeasiswaController;
use App\Http\Controllers\RegisterBesiswaUserController;
use App\Http\Controllers\HasilController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

Auth::routes();
/*------------------------------------------
--------------------------------------------
All Normal Users Routes List
--------------------------------------------
--------------------------------------------*/
Route::middleware(['auth', 'user-access:user'])
->name('user.')
->group(function () {
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/user/hasil', [HasilController::class, 'index'])->name('hasil.data');

//Register Beasiswa
Route::resource('user/register', RegisterBesiswaUserController::class);
Route::get('/user/searchRegister', [RegisterBesiswaUserController::class, 'search'])->name('search.register');
Route::get('/user/cetak_register', [RegisterBesiswaUserController::class, 'register_cetak_pdf'])->name('cetak.register');
Route::get('/user/files/{file}', [RegisterBesiswaUserController::class, 'download'])->name('download.file');
});
/*------------------------------------------
--------------------------------------------
All Admin Routes List
--------------------------------------------
--------------------------------------------*/
Route::middleware(['auth', 'user-access:admin'])->group(function () {
Route::get('/admin/home', [HomeController::class, 'adminHome'])->name('admin.home');
Route::get('/admin/hasil', [HasilController::class, 'index'])->name('admin.hasil.data');

//Beasiswa Master Route
Route::resource('admin/beasiswa', BeasiswaController::class);
Route::get('/admin/dataBeasiswa', [BeasiswaController::class, 'index'])->name('admin.beasiswa.master');
Route::get('/beasiswa', [BeasiswaController::class, 'json'])->name('beasiswaJson');
Route::get('/admin/cetak_beasiswa', [BeasiswaController::class, 'cetak_pdf'])->name('admin.cetak.beasiswa');
Route::get('/admin/search', [BeasiswaController::class, 'search'])->name('admin.search');

//Register Beasiswa
Route::resource('beasiswa/register', RegisterBeasiswaController::class);
Route::get('/beasiswa/searchRegister', [RegisterBeasiswaController::class, 'search'])->name('admin.search.register');
Route::get('/cetak_register', [RegisterBeasiswaController::class, 'register_cetak_pdf'])->name('admin.cetak.register');
Route::get('/files/{file}', [RegisterBeasiswaController::class, 'download'])->name('admin.download.file');
Route::post('/beasiswa/verifikasi', [RegisterBeasiswaController::class, 'verifikasi'])->name('admin.verifikasi');

 });

resources/views/adminHome.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <nav class=" container navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ route('beasiswa.index') }}">Master Data Beasiswa</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ route('register.index') }}"> Register Beasiswa</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ route('admin.hasil.data') }}">Hasil</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <br>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard Admin</div>
                <div class="card-body">
                    @if(session('login-success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('login-success') }}
                        </div>
                    @endif
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <b><h3>Selamat Datang di Sistem Informasi Beasiswa ,{{ Auth::user()->name }}</h3></b>
                    anda login sebagai <b>{{ Auth::user()->type }}</b>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <nav class=" container navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ route('user.register.index') }}">Add Beasiswa</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ route('user.hasil.data') }}">Hasil</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <br>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
            <div class="card-header">Dashboard Mahsiswa</div>
                <div class="card-body">
                    @if(session('login-success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('login-success') }}
                        </div>
                    @endif
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <b><h3>Selamat Datang di Sistem Informasi Beasiswa ,{{ Auth::user()->name }}</h3></b>
                    anda login sebagai <b>{{ Auth::user()->type }}</b>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection