routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\BeasiswaController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\RegisterBeasiswaController;
use App\Http\Controllers\RegisterBesiswaUserController;
use App\Http\Controllers\HasilController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

Auth::routes();
/*------------------------------------------
--------------------------------------------
All Normal Users Routes List
--------------------------------------------
--------------------------------------------*/
Route::middleware(['auth', 'user-access:user'])
->name('user.')
->group(function () {
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/user/hasil', [HasilController::class, 'index'])->name('hasil.data');

//Register Beasiswa
Route::resource('user/register', RegisterBesiswaUserController::class);
Route::get('/user/searchRegister', [RegisterBesiswaUserController::class, 'search'])->name('search.register');
Route::get('/user/cetak_register', [RegisterBesiswaUserController::class, 'register_cetak_pdf'])->name('cetak.register');
Route::get('/user/files/{file}', [RegisterBesiswaUserController::class, 'download'])->name('download.file');
});
/*------------------------------------------
--------------------------------------------
All Admin Routes List
--------------------------------------------
--------------------------------------------*/
Route::middleware(['auth', 'user-access:admin'])->group(function () {
Route::get('/admin/home', [HomeController::class, 'adminHome'])->name('admin.home');
Route::get('/admin/hasil', [HasilController::class, 'index'])->name('admin.hasil.data');

//Beasiswa Master Route
Route::resource('admin/beasiswa', BeasiswaController::class);
Route::get('/admin/dataBeasiswa', [BeasiswaController::class, 'index'])->name('admin.beasiswa.master');
Route::get('/beasiswa', [BeasiswaController::class, 'json'])->name('beasiswaJson');
Route::get('/admin/cetak_beasiswa', [BeasiswaController::class, 'cetak_pdf'])->name('admin.cetak.beasiswa');
Route::get('/admin/search', [BeasiswaController::class, 'search'])->name('admin.search');

//Register Beasiswa
Route::resource('beasiswa/register', RegisterBeasiswaController::class);
Route::get('/beasiswa/searchRegister', [RegisterBeasiswaController::class, 'search'])->name('admin.search.register');
Route::get('/cetak_register', [RegisterBeasiswaController::class, 'register_cetak_pdf'])->name('admin.cetak.register');
Route::get('/files/{file}', [RegisterBeasiswaController::class, 'download'])->name('admin.download.file');
Route::post('/beasiswa/verifikasi', [RegisterBeasiswaController::class, 'verifikasi'])->name('admin.verifikasi');

 });

app/Models/RegisterBeasiswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RegisterBeasiswa extends Model
{
    use HasFactory;
    protected $fillable = [
        'name', 'file','nomorHp','semester','ipk','beasiswa_id','image'
    ];

}

app/Http/Controllers/RegisterBeasiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\RegisterBeasiswa;
use App\Models\Beasiswa;

use Yajra\DataTables\Datatables;
use PDF;
class RegisterBeasiswaController extends Controller
{
    public function index()
    {
        $data = RegisterBeasiswa::latest()->paginate(5);

        return view('register-beasiswa.index', compact('data'))->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        $beasiswa = Beasiswa::all();
        
        return view('register-beasiswa.create', compact('beasiswa'));
    }

    public function store(Request $request)
    {
        $request->validate([
        'name' => 'required|unique:register_beasiswas',
        'email' => 'required|regex:/(.+)@(.+)\.(.+)/i',
        'nomorHp' => 'required|numeric|digits:12',
        'semester' => 'required',
        'beasiswa_id' => 'required',
        'file' => 'required|mimes:csv,txt,xlx,xls,pdf,jpg,jpeg,zip|max:2048'
        ]);
        if($request->file()) {
            $fileName = time().'_'.$request->file->getClientOriginalName();
            $filePath = $request->file('file')->storeAs('uploads', $fileName, 'public');
            $register = new RegisterBeasiswa;
            $register->name = $request->name;
            $register->email = $request->email;
            $register->nomorHp = $request->nomorHp;
            $register->semester = $request->semester;
            $register->ipk = rand (2.9*10, 3.4*10) / 10;
            $register->beasiswa_id = $request->beasiswa_id;
            $register->file = '/storage/' . $filePath;
            $register->save();
            return redirect()->route('register.index')
            ->with('sukses','Data Register Beasiswa telah Ditambahkan.');
        }
    }
    public function update(Request $request, $id)
    {
            $request->validate([
                'name' => 'required|unique:register_beasiswas',
                'email' => 'required|regex:/(.+)@(.+)\.(.+)/i',
                'nomorHp' => 'required|numeric|digits:12',
                'semester' => 'required',
                'beasiswa_id' => 'required',
                ]);

            // if($request->file()) {
            // $fileName = time().'_'.$request->file->getClientOriginalName();
            // $filePath = $request->file('file')->storeAs('uploads', $fileName, 'public');
            $register = RegisterBeasiswa::find($id);
            $register->name = $request->name;
            $register->email = $request->email;
            $register->nomorHp = $request->nomorHp;
            $register->semester = $request->semester;
            $register->ipk = rand (2.9*10, 3.4*10) / 10;
            $register->beasiswa_id = $request->beasiswa_id;
            // $register->file = '/storage/' . $filePath;
            $register->save();
            return redirect()->route('register.index')
            ->with('sukses','Data Register Beasiswa telah Diubah.');
        // }
    }
    public function verifikasi(Request $request, $id)
    {
        $beasiswa = RegisterBeasiswa::find($id);
        $beasiswa->status_ajuan = 1;
        $beasiswa->save($id);
        dd($beasiswa);
            return redirect()->route('register.index')
        ->with('sukses','Data  Telah berhasil Di delete');
    }

    public function download($file){
        
        return response()->download(storage_path('/storage/app/public/uploads/'.$file));
     }

    public function show($id)
    {
        
        $registerbeasiswa = RegisterBeasiswa::find($id);

        return view('register-beasiswa.show',compact('registerbeasiswa'));
    }

    
    public function destroy(RegisterBeasiswa $beasiswa,$id)
    {

        $beasiswa->delete($id);
            return redirect()->route('register.index')
        ->with('sukses','Data  Telah berhasil Di delete');
    }
    
    public function edit($id)
    {
        $beasiswa = RegisterBeasiswa::find($id);
        $biasis = Beasiswa::all();

        return view('register-beasiswa.edit',compact('beasiswa','biasis','id'));
    }

    public function search(Request $request)
    {
        $keyword = $request->search;
        $data = RegisterBeasiswa::where('name', 'like', "%" . $keyword . "%")
        ->orWhere('email', 'like', "%" . $keyword . "%")
        ->orWhere('nomorHp', 'like', "%" . $keyword . "%")
        ->orWhere('semester', 'like', "%" . $keyword . "%")->paginate(5);
        return view('register-beasiswa.index', compact('data'))->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function register_cetak_pdf()
    {
    	$registerbeasiswa = RegisterBeasiswa::all();
 
    	$pdf = PDF::loadview('register-beasiswa.report-register-beasiswa',['registerbeasiswa'=>$registerbeasiswa]);
    	return $pdf->download('laporan-register-beasiswa-pdf');
    }

}

resources/views/register-beasiswa/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container mt-2">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left mb-2">
                    <h2>Tambah Register</h2>
                </div>
            </div>
        </div>
        <br>
        @if(session('status'))
        <div class="alert alert-success mb-1 mt-1">
        {{ session('status') }}
        </div>
        @endif
        @if(Auth::user()->type != "admin")
            <form action="{{ route('user.register.store') }}" method="POST" enctype="multipart/form-data">
        @else
            <form action="{{ route('register.store') }}" method="POST" enctype="multipart/form-data">
        @endif
            @csrf
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Nama Mahasiswa:</strong>
                        <input type="text" name="name" class="form-control" placeholder="Nama Mahasiswa">
                        @error('name')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Email:</strong>
                        <input type="email" name="email" class="form-control" placeholder="Email Mahasiswa">
                        @error('email')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Handphone:</strong>
                        <input type="number" name="nomorHp" class="form-control" placeholder="Nomor Handphone">
                        @error('nomorHp')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Semester</strong>

                        <select class="form-control" name="semester"  onclick="cek_data()" >
                            <option selected>Pilih Semester</option>
                            <option value="1">Satu</option>
                            <option value="2">Dua</option>
                            <option value="3">Tiga</option>
                            <option value="4">Empat</option>
                            <option value="5">Lima</option>
                            <option value="6">Enam</option>
                            <option value="7">Tujuh</option>
                            <option value="8">Delapan</option>
                        </select>
                        @error('target')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>IPK:</strong>
                        <input type="text" id="ipk" name="ipk" class="form-control" placeholder="Nama IPK"
                         value={{rand (2.9*10, 3.4*10) / 10}} disabled="true">
                        @error('ipk')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Beasiswa:</strong>
                        <select class="form-control" id="beasiswa_id" name="beasiswa_id">
                        @foreach ($beasiswa as $beasis)
                            <option value="{{ $beasis->id }}">{{ $beasis->beasiswa_name }}</option>
                        @endforeach
                        </select>
                        @error('beasiswa_id')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Upload Berkas:</strong>
                        <input type="file" name="file" class="form-control custom-file-input" id="chooseFile">
                        @error('beasiswa_id')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>

            </div>
            <br>

                <button type="submit" class="btn btn-primary ml-3">Tambah</button>
                <input class="btn btn-warning" type="reset" value="reset">
                @if(Auth::user()->type == "admin")
                    <a class="btn btn-success" href="{{ route('register.index') }}"> Back</a>
                @else
                    <a class="btn btn-success" href="{{ route('user.register.store') }}"> Back</a>
                @endif
        </form>
        </div>
       
        <script type="text/javascript">
            function cek_data(){
            var ipk = document.getElementById("ipk").value;
            if (ipk ==3 || ipk <= 3) {
                // console.log("disabled")
                document.getElementById("chooseFile").disabled = true;
                document.getElementById("beasiswa_id").disabled = true;
            }else{
                // console.log("enabled");
                document.getElementById("chooseFile").disabled = false;
                document.getElementById("beasiswa_id").disabled = false;
            }
            console.log(ipk);
            }
    </script>
@endsection

resources/views/register-beasiswa/hasil.blade.php
@extends('layouts.app')
@section('content')

<nav class=" container navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                @if(Auth::user()->type != "admin")
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('user.register.index') }}">Add Beasiswa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('user.hasil.data') }}">Hasil</a>
                    </li>

                @else
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('beasiswa.index') }}">Master Data Beasiswa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('register.index') }}"> Register Beasiswa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('admin.hasil.data') }}">Hasil</a>
                    </li>
                @endif
           

                </ul>
            </div>
        </div>
    </nav>
<div class="container mt-2">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
            <h2> Data Permohonan Beasiswa</h2>
            </div>

        </div>
        @if(Auth::user()->type != "admin")
        <form class="form" method="get" action="{{ route('user.search.register') }}">

        @else
        <form class="form" method="get" action="{{ route('admin.search.register') }}">

        @endif
            <div class="form-group w-100 mb-3">
                <input type="text" name="search" class="form-control w-75 d-inline" id="search" placeholder="Masukkan pencarian data">
                <button type="submit" class="btn btn-primary mb-1">Cari</button>
            </div>
        </form>
        <!-- Start kode untuk form pencarian -->
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
    </div>
@if ($message = Session::get('success'))
<div class="alert alert-success">
<p>{{ $message }}</p>
</div>
@endif
<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Nama</th>
        <th>Email</th>
        <th>Nomor Handphone</th>
        <th>Semester</th>
        <th>IPK</th>
        <th>Beasiswa</th>
        <th>File</th>
        <th>Status Ajuan</th>
    </tr>
        @php $i=1 @endphp

        @foreach ($data as $register)
        @php
        $child = DB::table('beasiswas')->select('beasiswa_name','register_beasiswas.beasiswa_id')
            ->join('register_beasiswas','register_beasiswas.beasiswa_id','=','beasiswas.id')
            ->where('beasiswa_id',$register->beasiswa_id)->first();
        @endphp
<tr>
    <td>{{ $i++ }}</td>
    <td>{{ $register->name }}</td>
    <td>{{ $register->email }}</td>
    <td>{{ $register->nomorHp }}</td>
    <td>{{ $register->semester }}</td>
    <td>
        @if($register->ipk ==null)
            <b>-</b>
        @else
            <b>{{ $register->ipk }}</b>
        @endif
    </td>
    <td>{{ $child->beasiswa_name }}</td>
    <td>
        @if(Auth::user()->type != "admin")
            <a href="{!! route('user.download.file', substr($register->file,17)) !!}">{{substr($register->file,17)}}</a>

        @else
            <a href="{!! route('admin.download.file', substr($register->file,17)) !!}">{{substr($register->file,17)}}</a>
        @endif
    </td>
    <td>
        @if($register->status_ajuan ==0)
            <b>Belum Diverifikasi</b>
        @else
            <b>Sudah Diverifikasi</b>
        @endif
    </td>
        @if(Auth::user()->type != "admin")
        <td>
            <form action="{{ route('admin.verifikasi',$register->id) }}" method="Post">
            @csrf
            @method('POST')
            <button type="submit" class="btn btn-warning">Verifikasi</button>
            </form>
        </td>
        @else
    
        @endif
   
</tr>
@endforeach
</table>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Pemberitahuan</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Untuk melakukan perubahan data pemohon beasiswa silahkan hubungi admin..
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{!! $data->links() !!}
@endsection

resources/views/register-beasiswa/index.blade.php
@extends('layouts.app')
@section('content')

<nav class=" container navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                @if(Auth::user()->type != "admin")
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('user.register.index') }}">Add Beasiswa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('user.hasil.data') }}">Hasil</a>
                    </li>

                @else
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('beasiswa.index') }}">Master Data Beasiswa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('register.index') }}"> Register Beasiswa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('admin.hasil.data') }}">Hasil</a>
                    </li>
                @endif
           

                </ul>
            </div>
        </div>
    </nav>
<div class="container mt-2">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
            <h2> Input Register Beasiswa</h2>
            </div>

            <div class="pull-right mb-2">
            @if(Auth::user()->type != "admin")
            <a class="btn btn-success" href="{{ route('user.register.create') }}"> Create Register Beasiswa</a>
            <a href="{{ route('user.cetak.register') }}" class="btn btn-primary" target="_blank">Cetak Report</a>

            @else
            <a class="btn btn-success" href="{{ route('register.create') }}"> Create Register Beasiswa</a>
            <a href="{{ route('admin.cetak.register') }}" class="btn btn-primary" target="_blank">Cetak Report</a>

            @endif
           

            </div>
        </div>
        @if(Auth::user()->type != "admin")
        <form class="form" method="get" action="{{ route('user.search.register') }}">

        @else
        <form class="form" method="get" action="{{ route('admin.search.register') }}">

        @endif
            <div class="form-group w-100 mb-3">
                <input type="text" name="search" class="form-control w-75 d-inline" id="search" placeholder="Masukkan pencarian data">
                <button type="submit" class="btn btn-primary mb-1">Cari</button>
            </div>
        </form>
        <!-- Start kode untuk form pencarian -->
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
    </div>
@if ($message = Session::get('success'))
<div class="alert alert-success">
<p>{{ $message }}</p>
</div>
@endif
<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Nama</th>
        <th>Email</th>
        <th>Nomor Handphone</th>
        <th>Semester</th>
        <th>IPK</th>
        <th>Beasiswa</th>
        <th>File</th>
        <th>Status Ajuan</th>
        <th width="280px">Action</th>
    </tr>
        @php $i=1 @endphp

        @foreach ($data as $register)
        @php
        $child = DB::table('beasiswas')->select('beasiswa_name','register_beasiswas.beasiswa_id')
            ->join('register_beasiswas','register_beasiswas.beasiswa_id','=','beasiswas.id')
            ->where('beasiswa_id',$register->beasiswa_id)->first();
        @endphp
<tr>
    <td>{{ $i++ }}</td>
    <td>{{ $register->name }}</td>
    <td>{{ $register->email }}</td>
    <td>{{ $register->nomorHp }}</td>
    <td>{{ $register->semester }}</td>
    <td>
        @if($register->ipk ==null)
            <b>-</b>
        @else
            <b>{{ $register->ipk }}</b>
        @endif
    </td>
    <td>{{ $child->beasiswa_name }}</td>
    <td>
        @if(Auth::user()->type != "admin")
            <a href="{!! route('user.download.file', substr($register->file,17)) !!}">{{substr($register->file,17)}}</a>

        @else
            <a href="{!! route('admin.download.file', substr($register->file,17)) !!}">{{substr($register->file,17)}}</a>
        @endif
    </td>
    <td>
        @if($register->status_ajuan ==0)
            <b>Belum Diverifikasi</b>
        @else
            <b>Sudah Diverifikasi</b>
        @endif
    </td>
    <td>
        @if(Auth::user()->type != "admin")
        <form action="{{ route('user.register.destroy',$register->id) }}" method="Post">

        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Edit
        </button>
        <a class="btn btn-info" href="{{ route('user.register.show',$register->id) }}">Details</a>
        @else
        <form action="{{ route('register.destroy',$register->id) }}" method="Post">

        <a class="btn btn-primary" href="{{ route('register.edit',$register->id) }}">Edit</a>
        <a class="btn btn-info" href="{{ route('register.show',$register->id) }}">Details</a>
        @endif
        @csrf
        @method('DELETE')
        <button style="display:none;" type="submit" class="btn btn-danger">Delete</button>
    </form>
    </td>
</tr>
@endforeach
</table>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Pemberitahuan</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Untuk melakukan perubahan data pemohon beasiswa silahkan hubungi admin..
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>
{!! $data->links() !!}
@endsection

resources/views/register-beasiswa/report-register-beasiswa.blade.php
@php
    use Illuminate\Support\Carbon;

@endphp
<!DOCTYPE html>
<html>
<head>
	<title>Laporan Pendaftar Beasiswa</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<style>
    hr{
        border: 0;
        border-top: 3px double #8c8c8c;
    }
</style>
<body>
	<style type="text/css">
		table tr td,
		table tr th{
			font-size: 9pt;
		}
	</style>
	<center>
		<h5>Laporan Pendaftar Beasiswa Terupdate</h4>
	</center>
    <hr>
	<table class='table table-bordered'>
		<thead>
			<tr>
				<th>No</th>
				<th>Nama</th>
				<th>Email</th>
				<th>Nomor Handphone</th>
				<th>Semester</th>
				<th>IPK</th>
				<th>Beasiswa</th>
				<th>Status Ajuan</th>
			</tr>
		</thead>
		<tbody>
			@php $i=1 @endphp
			@foreach($registerbeasiswa as $register)
			@php
			$child = DB::table('beasiswas')->select('beasiswa_name','register_beasiswas.beasiswa_id')
				->join('register_beasiswas','register_beasiswas.beasiswa_id','=','beasiswas.id')
				->where('beasiswa_id',$register->beasiswa_id)->first();
			@endphp
			<tr>
				<td>{{ $i++ }}</td>
				<td>{{ $register->name }}</td>
				<td>{{ $register->email }}</td>
				<td>{{ $register->nomorHp }}</td>
				<td>{{ $register->semester }}</td>
				<td>
					@if($register->ipk ==null)
						<b>-</b>
					@else
						<b>{{ $register->ipk }}</b>
					@endif
				</td>
				<td>{{ $child->beasiswa_name }}</td>
				
				<td>
					@if($register->status_ajuan ==0)
						<b>Belum Diverifikasi</b>
					@else
						<b>Sudah Diverifikasi</b>
					@endif
				</td>
			</tr>
			@endforeach
		</tbody>
	</table>
    <small class="pull-right">Bandung ,{{ Carbon::today()->format('l jS \\of F Y')}}</small>
    <br>
    <br>
    <br>
    <small>{{ Auth::user()->name }}</small>
</body>
</html>

resources/views/register-beasiswa/show.blade.php
@extends('layouts.app')
  
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div>
                <h2> Details Pemohon Beasiswa</h2>
            </div>
            <div>
            @if(Auth::user()->type != "admin")
            <a class="btn btn-primary" href="{{ route('user.register.index') }}"> Back</a>

            @else
            <a class="btn btn-primary" href="{{ route('register.index') }}"> Back</a>

            @endif
            </div>
        </div>
    </div>
    @php
        $child = DB::table('beasiswas')->select('beasiswa_name','register_beasiswas.beasiswa_id')
            ->join('register_beasiswas','register_beasiswas.beasiswa_id','=','beasiswas.id')
            ->where('beasiswa_id',$registerbeasiswa->beasiswa_id)->first();
        @endphp
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama:</strong>
                {{ $registerbeasiswa->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $registerbeasiswa->email}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nomor Hp:</strong>
                {{ $registerbeasiswa->nomorHp}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Semester:</strong>
                
                {{ $registerbeasiswa->semester}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Ipk:</strong>
                @if($registerbeasiswa->ipk ==null)
                    <b>-</b>
                @else
                    <b>{{ $registerbeasiswa->ipk }}</b>
                @endif
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Beasiswa:</strong>
                    <b>{{ $child->beasiswa_name }}</b>
            </div>
        </div>
    </div>
@endsection