routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\BeasiswaController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\RegisterBeasiswaController;
use App\Http\Controllers\RegisterBesiswaUserController;
use App\Http\Controllers\HasilController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

Auth::routes();
/*------------------------------------------
--------------------------------------------
All Normal Users Routes List
--------------------------------------------
--------------------------------------------*/
Route::middleware(['auth', 'user-access:user'])
->name('user.')
->group(function () {
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/user/hasil', [HasilController::class, 'index'])->name('hasil.data');

//Register Beasiswa
Route::resource('user/register', RegisterBesiswaUserController::class);
Route::get('/user/searchRegister', [RegisterBesiswaUserController::class, 'search'])->name('search.register');
Route::get('/user/cetak_register', [RegisterBesiswaUserController::class, 'register_cetak_pdf'])->name('cetak.register');
Route::get('/user/files/{file}', [RegisterBesiswaUserController::class, 'download'])->name('download.file');
});
/*------------------------------------------
--------------------------------------------
All Admin Routes List
--------------------------------------------
--------------------------------------------*/
Route::middleware(['auth', 'user-access:admin'])->group(function () {
Route::get('/admin/home', [HomeController::class, 'adminHome'])->name('admin.home');
Route::get('/admin/hasil', [HasilController::class, 'index'])->name('admin.hasil.data');

//Beasiswa Master Route
Route::resource('admin/beasiswa', BeasiswaController::class);
Route::get('/admin/dataBeasiswa', [BeasiswaController::class, 'index'])->name('admin.beasiswa.master');
Route::get('/beasiswa', [BeasiswaController::class, 'json'])->name('beasiswaJson');
Route::get('/admin/cetak_beasiswa', [BeasiswaController::class, 'cetak_pdf'])->name('admin.cetak.beasiswa');
Route::get('/admin/search', [BeasiswaController::class, 'search'])->name('admin.search');

//Register Beasiswa
Route::resource('beasiswa/register', RegisterBeasiswaController::class);
Route::get('/beasiswa/searchRegister', [RegisterBeasiswaController::class, 'search'])->name('admin.search.register');
Route::get('/cetak_register', [RegisterBeasiswaController::class, 'register_cetak_pdf'])->name('admin.cetak.register');
Route::get('/files/{file}', [RegisterBeasiswaController::class, 'download'])->name('admin.download.file');
Route::post('/beasiswa/verifikasi', [RegisterBeasiswaController::class, 'verifikasi'])->name('admin.verifikasi');

 });

app/Models/Beasiswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Beasiswa extends Model
{
    use HasFactory;
    protected $fillable = [
        'beasiswa_name', 'jenis','donatur'
    ];
}

app/Http/Controllers/BeasiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Beasiswa;
use Yajra\DataTables\Datatables;
use PDF;

class BeasiswaController extends Controller
{
    public function json(){
        return Datatables::of(Beasiswa::all())->make(true);
    }

    public function index()
    {
        $data = Beasiswa::latest()->paginate(5);

        return view('beasiswa.index', compact('data'))->with('i', (request()->input('page', 1) - 1) * 5);
    }
    public function create()
    {
        return view('beasiswa.create');
    }
    public function store(Request $request)
    {
        $request->validate([
        'beasiswa_name' => 'required|unique:beasiswas',
        'deskripsi' => 'required',
        'jenis' => 'required',
        'donatur' => 'required'
        ]);
        $beasiswa = new Beasiswa;
        $beasiswa->beasiswa_name = $request->beasiswa_name;
        $beasiswa->deskripsi = $request->deskripsi;
        $beasiswa->jenis = $request->jenis;
        $beasiswa->donatur = $request->donatur;
        $beasiswa->save();
        return redirect()->route('beasiswa.index')
        ->with('sukses','Data Master Beasiswa telah Ditambahkan.');
    }

    public function show(Beasiswa $beasiswa)
    {
        return view('beasiswa.show',compact('beasiswa'));
    }
    
    public function edit(Beasiswa $beasiswa)
    {
        return view('beasiswa.edit',compact('beasiswa'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'beasiswa_name' => 'required|unique:beasiswas',
            'deskripsi' => 'required',
            'jenis' => 'required',
            'donatur' => 'required'
            ]);
        $beasiswa = Beasiswa::find($id);
        $beasiswa->beasiswa_name = $request->beasiswa_name;
        $beasiswa->deskripsi = $request->deskripsi;
        $beasiswa->jenis = $request->jenis;
        $beasiswa->donatur = $request->donatur;
        $beasiswa->save();
        return redirect()->route('beasiswa.index')
        ->with('sukses','Data Beasiswa Telah Berhasil Di Update');
    }

    public function destroy(Beasiswa $beasiswa)
    {
        $beasiswa->delete();
            return redirect()->route('beasiswa.index')
        ->with('sukses','Data Beasiswa Telah berhasil Di delete');
    }

    public function cetak_pdf()
    {
    	$beasiswa = Beasiswa::all();
 
    	$pdf = PDF::loadview('beasiswa.report-beasiswa',['beasiswa'=>$beasiswa]);
    	return $pdf->download('laporan-beasiswa-pdf');
    }

    public function search(Request $request)
    {
        $keyword = $request->search;
        $data = Beasiswa::where('beasiswa_name', 'like', "%" . $keyword . "%")
        ->orWhere('jenis', 'like', "%" . $keyword . "%")
        ->orWhere('donatur', 'like', "%" . $keyword . "%")->paginate(5);
        return view('beasiswa.index', compact('data'))->with('i', (request()->input('page', 1) - 1) * 5);
    }
}

resources/views/beasiswa/create.blade.php
@extends('layouts.app')
@section('content')

    <div class="container mt-2">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left mb-2">
                    <h2>Tambah Beasiswa</h2>
                </div>
            </div>
        </div>
        <br>
        @if(session('status'))
        <div class="alert alert-success mb-1 mt-1">
        {{ session('status') }}
        </div>
        @endif
        <form action="{{ route('beasiswa.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Nama Beasiswa:</strong>
                        <input type="text" name="beasiswa_name" class="form-control" placeholder="Nama Beasiswa">
                        @error('beasiswa_name')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Deskripsi Beasiswa:</strong>
                        <textarea id="trmp" style="white-space: normal;" type="text" class="form-control" name="deskripsi" placeholder="Deskripsi Beasiswa">
                        </textarea>
                        @error('deskripsi')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Jenis Beasiswa</strong>

                        <select name="jenis" class="form-control custom-select @error('target') is-invalid @enderror">
                            <option value="" selected disabled hidden>Pilih Jenis Beasiswa</option>
                            <option value="akademik" @if(old( 'target')=='akademik' ) selected @endif>Akademik</option>
                            <option value="nonAkademik" @if(old( 'target')=='nonAkademik' ) selected @endif>Non-Akademik</option>
                        </select>
                        @error('target')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Donatur:</strong>
                        <input type="text" name="donatur" class="form-control" placeholder="Nama Donatur">
                        @error('donatur')
                        <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
            </div>
            <br>
                <button type="submit" class="btn btn-primary ml-3">Tambah</button>
                <input class="btn btn-warning" type="reset" value="reset">
                <a class="btn btn-success" href="{{ route('beasiswa.index') }}"> Back</a>
        </form>
        </div>

@endsection

resources/views/beasiswa/edit.blade.php
@extends('layouts.app')
@section('content')
<style>
    textarea {
  white-space: pre;
  overflow-wrap: normal;
  overflow-x: scroll;
}
</style>
<div class="container mt-2">
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
        <h2>Edit Beasiswa</h2>
        </div>
        </div>
    </div>
    @if(session('status'))
    <div class="alert alert-success mb-1 mt-1">
    {{ session('status') }}
    </div>
@endif
    <form action="{{ route('beasiswa.update',$beasiswa->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
            <strong>Nama Beasiswa:</strong>
            <input type="text" name="beasiswa_name" value="{{ $beasiswa->beasiswa_name }}" class="form-control" placeholder="Nama Beasiswa">
            @error('beasiswa_name')
            <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
            @enderror
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Deskripsi Beasiswa:</strong>
         
                <textarea style="white-space: normal;" id="trmp" name = "deskripsi" rows="10" cols="50" onKeyPress class="form-control">
                {{ $beasiswa->deskripsi }}
                </textarea>
                @error('deskripsi')
                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
            </div>
        </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Jenis Beasiswa</strong>
                        <select class="form-control" id="jenis" name="jenis">
                            <option value="akademik" {{($beasiswa->jenis ==='akademik') ? 'selected' : ''}}> Akademik </option>
                            <option value="nonAkademik" {{($beasiswa->jenis ==='nonAkademik') ? 'selected' : ''}}> Non-Akademik </option>
                        </select>
                    
                        @error('target')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Donatur:</strong>
                <input type="text" name="donatur" value="{{ $beasiswa->donatur }}" class="form-control" placeholder="Donatur Beasiswa">
                @error('donatur')
                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
            </div>
        </div>
        </div>
        <br>
    <button type="submit" class="btn btn-primary ml-3">Edit Beasiswa</button>
    <a class="btn btn-success" href="{{ route('beasiswa.index') }}"> Back</a>

    </div>
    </form>
</div>
@endsection

resources/views/beasiswa/index.blade.php
@extends('layouts.app')
@section('content')

<nav class=" container navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    @if(Auth::user()->type == "admin")
                        <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('beasiswa.index') }}">Master Data Beasiswa</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('register.index') }}"> Register Beasiswa</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('admin.hasil.data') }}">Hasil</a>
                    </li>
                    @else
                        <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('beasiswa.index') }}">Master Data Beasiswa</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('register.index') }}"> Register Beasiswa</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('admin.hasil.data') }}">Hasil</a>
                        </li>
                    @endif


                </ul>
            </div>
        </div>
    </nav>
<div class="container mt-2">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
            <h2> Input data Master Beasiswa</h2>
            </div>

            <div class="pull-right mb-2">
            <a class="btn btn-success" href="{{ route('beasiswa.create') }}"> Create Master Beasiswa</a>
            <a href="{{ route('admin.cetak.beasiswa') }}" class="btn btn-primary" target="_blank">Cetak Report</a>

            </div>
        </div>
        <form class="form" method="get" action="{{ route('admin.search') }}">
            <div class="form-group w-100 mb-3">
                <input type="text" name="search" class="form-control w-75 d-inline" id="search" placeholder="Masukkan pencarian data">
                <button type="submit" class="btn btn-primary mb-1">Cari</button>
            </div>
        </form>
        <!-- Start kode untuk form pencarian -->
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
    </div>
@if ($message = Session::get('success'))
<div class="alert alert-success">
<p>{{ $message }}</p>
</div>
@endif
<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Beasiswa</th>
        <th>Deskripsi</th>
        <th>Jenis</th>
        <th>Donatur</th>
        <th width="280px">Action</th>
    </tr>
            @php $i=1 @endphp
@foreach ($data as $beasiswa)
<tr>
    <td>{{ $i++ }}</td>
    <td>{{ $beasiswa->beasiswa_name }}</td>
    <td>{{ $beasiswa->deskripsi }}</td>
    <td>{{ $beasiswa->jenis }}</td>
    <td>{{ $beasiswa->donatur }}</td>
    <td>
    <form action="{{ route('beasiswa.destroy',$beasiswa->id) }}" method="Post">
        <a class="btn btn-primary" href="{{ route('beasiswa.edit',$beasiswa->id) }}">Edit</a>
        <a class="btn btn-info" href="{{ route('beasiswa.show',$beasiswa->id) }}">Details</a>
        @csrf
        @method('DELETE')
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
    </td>
</tr>
@endforeach
</table>
{!! $data->links() !!}
@endsection

resources/views/beasiswa/report-beasiswa.blade.php
@php
    use Illuminate\Support\Carbon;

@endphp
<!DOCTYPE html>
<html>
<head>
	<title>Laporan Beasiswa</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<style>
    hr{
        border: 0;
        border-top: 3px double #8c8c8c;
    }
</style>
<body>
	<style type="text/css">
		table tr td,
		table tr th{
			font-size: 9pt;
		}
	</style>
	<center>
		<h5>Laporan Data Beasiswa Terupdate</h4>
	</center>
    <hr>
	<table class='table table-bordered'>
		<thead>
			<tr>
				<th>No</th>
                <th>Beasiswa</th>
                <th>Deskripsi</th>
                <th>Jenis</th>
                <th>Donatur</th>
			</tr>
		</thead>
		<tbody>
			@php $i=1 @endphp
			@foreach($beasiswa as $p)
			<tr>
				<td>{{ $i++ }}</td>
				<td>{{$p->beasiswa_name}}</td>
				<td>{{$p->deskripsi}}</td>
				<td>{{$p->jenis}}</td>
				<td>{{$p->donatur}}</td>
			</tr>
			@endforeach
		</tbody>
	</table>
    <small class="pull-right">Bandung ,{{ Carbon::today()->format('l jS \\of F Y')}}</small>
    <br>
    <br>
    <br>
    <small>{{ Auth::user()->name }}</small>
</body>
</html>

resources/views/beasiswa/show.blade.php
@extends('layouts.app')
  
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div>
                <h2> Details Beasiswa</h2>
            </div>
            <div>
                <a class="btn btn-primary" href="{{ route('beasiswa.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Beasiswa:</strong>
                {{ $beasiswa->beasiswa_name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Deskripsi:</strong>
                {{ $beasiswa->deskripsi}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Jenis:</strong>
                {{ $beasiswa->jenis}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Donatur:</strong>
                {{ $beasiswa->jenis}}
            </div>
        </div>
    </div>
@endsection